export enum CategoryEnum {
  A = 'orzecznictwo - dzieci do 16 r. ż. - rehabilitacja lub edukacja',
  B = 'orzecznictwo - dzieci do 16 r. ż. - inne',
  C = 'orzecznictwo - dzieci od 16 do 18 r. ż. - rehabilitacja lub edukacja',
  D = 'orzecznictwo - dzieci od 16 do 18 r. ż. - inne',
  E = 'orzecznictwo - dorośli - rentowy',
  F = 'orzecznictwo - dorośli - pozarentowy',
  G = 'edukacja - przedszkole',
  H = 'edukacja - szkoła podstawowa',
  I = 'edukacja - szkoła ponadpodstawowa',
  J = 'rehabilitacja - zawodowa',
  K = 'rehabilitacja - społeczna - dzieci',
  L = 'rehabilitacja - społeczna - dorośli',
  M = 'rehabilitacja - lecznicza - dzieci',
  N = 'rehabilitacja - lecznicza - dorośli',
  O = 'opieka - dzieci - dzienny',
  P = 'opieka - dzieci - całodobowy',
  R = 'opieka - dorośli - dzienny',
  S = 'opieka - dorośli - całodobowy',
  T = 'inne wsparcie',
}
