export enum CategoryEnum {
  CERTIFICATION_CHILD_REHABILITATION = 'orzecznictwo - dzieci do 16 r. ż. - rehabilitacja lub edukacja',
  CERTIFICATION_CHILD_OTHER = 'orzecznictwo - dzieci do 16 r. ż. - inne',
  CERTIFICATION_TEENAGER_REHABILITATION = 'orzecznictwo - dzieci od 16 do 18 r. ż. - rehabilitacja lub edukacja',
  CERTIFICATION_TEENAGER_OTHER = 'orzecznictwo - dzieci od 16 do 18 r. ż. - inne',
  CERTIFICATION_ADULT_PENSION = 'orzecznictwo - dorośli - rentowy',
  CERTIFICATION_ADULT_NON_PENSION = 'orzecznictwo - dorośli - pozarentowy',
  EDUCATION_KINDERGARTEN = 'edukacja - przedszkole',
  EDUCATION_PRIMARY_SCHOOL = 'edukacja - szkoła podstawowa',
  EDUCATION_SECONDARY_SCHOOL = 'edukacja - szkoła ponadpodstawowa',
  REHABILITATION_PROFESSIONAL = 'rehabilitacja - zawodowa',
  REHABILITATION_SOCIAL_CHILD = 'rehabilitacja - społeczna - dzieci',
  REHABILITATION_SOCIAL_ADULT = 'rehabilitacja - społeczna - dorośli',
  REHABILITATION_MEDICAL_CHILD = 'rehabilitacja - lecznicza - dzieci',
  REHABILITATION_MEDICAL_ADULT = 'rehabilitacja - lecznicza - dorośli',
  CARE_CHILD_DAYTIME = 'opieka - dzieci - dzienny',
  CARE_CHILD_ALL_TIME = 'opieka - dzieci - całodobowy',
  CARE_ADULT_DAYTIME = 'opieka - dorośli - dzienny',
  CARE_ADULT_ALL_TIME = 'opieka - dorośli - całodobowy',
  OTHER = 'inne wsparcie',
}
